### ISSUE TITLE
Support non ASCII letter

### ISSUE THREAD

**Issue by cardil** [piecioshka/is-letter#15]
Add support for non ASCII letters, especially the polish ones.

I checked on NPM' runkit env, and the `isLetter('ą')` returned `false`

**Comment by piecioshka** [comment]
What about @y3ti's PR https://github.com/piecioshka/is-letter/pull/1?

**Comment by cardil** [comment]
Maybe that's just RunKit fault. I see the tests should assert this.

However strange.

**Comment by piecioshka** [comment]
I published a version with the current code, which adds support for `ą`.
Tested `is-letter`  v1.3.2:

![Screenshot 2023-11-25 at 22 33 50@2x](https://github.com/piecioshka/is-letter/assets/244935/4a09e282-8184-42cd-85d2-1966470d77c7)
